# Site settings

title: "Data Storage & Access for All"
email: cyberhelp@sesync.org
description: "Introduction to the principles and utility of relational database management systems."
baseurl: /introdb-lesson

# Jekyll Settings

markdown: kramdown
collections:
  - slides

# List files from _slide/ in order here (without the extension)
slide_sorter:
  - title
  - intro
  - goals
  - features
  - keys
  - sql
  - dtype
  