# Site

title: "Database Principles and Use"
email: cyberhelp@sesync.org
description: "Introduction to the principles and utility of relational database management systems."
baseurl: /introdb-lesson
# styleurl: https://cdn.rawgit.com/sesync-ci/lesson-stylesheets/1.0.0
styleurl: https://rawgit.com/sesync-ci/lesson-stylesheets/master
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.3.0
authors:
  - Ian Carroll
lesson: 3

# Slides

slide_sorter:
  - title
  - goals
  - intro
  - features
  - keys
#  - sql
  - join
  - dtype 
#  - extend
  - summary
  - solutions

# Jekyll

markdown: kramdown
collections:
  - slides
exclude:
  - README.md
  - build.R
  - "*.Rmd"

