# Site

title: Database Principles and Use
handouts:
 - worksheet.Rmd
 - data/README.md
tag: v0.3
lesson: 3
instructor: Benoît Parmentier
authors:
  - Ian Carroll
  - Mary Shelly

# Slides

slide_sorter:
  - goals
  - intro
#  - features
  - tables
  - server
#  - create
  - keys
  - untidy
#  - join
#  - dtype 
#  - extend
  - summary
#  - exercises

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v2.0/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
